### ISSUE TITLE
ftp can not -get a filename from a tuple, making it much less useful in scripts

### ISSUE THREAD

**Issue by Taywee** [jwoehr/ublu#11]

**Comment by jwoehr** [comment]
Can you describe this a little more, please?

**Comment by jwoehr** [comment]
Right. I really have to fix all that. Like I said, I'll work on it tomorrow.

**Comment by Taywee** [comment]
Sure, no problem.  Just making sure we have every issue I hit documented, so we don't miss anything.

**Comment by jwoehr** [comment]
Thanks, that's how I work best, detailed problem reports.

**Comment by jwoehr** [comment]
Taylor .. check out and build and try the `ftp` command now.
The older version is still there as `oldftp` so it will be easy to change scripts.
Make sure you get the ubluref too as the specs for the command have changed very much.

**Comment by jwoehr** [comment]
Did you ever try this out?

**Comment by Taywee** [comment]
Yes I did.  It appeared to work as expected.

**Comment by jwoehr** [comment]
Thanks!
