### ISSUE TITLE
Screenshots

### ISSUE THREAD

**Issue by jwoehr** [jwoehr/ublu#17]

**Comment by jwoehr** [comment]
![ubluwin](https://user-images.githubusercontent.com/4604036/27810879-ed42fa88-601c-11e7-9415-83437266c091.jpg)

**Comment by jwoehr** [comment]
![screen shot 2017-09-16 at 12 20 29 am](https://user-images.githubusercontent.com/4604036/30892141-33301764-a2f4-11e7-88e6-e7583866037e.jpg)

**Comment by ThePrez** [comment]
??

**Comment by jwoehr** [comment]
There was a time you had to open an issue on GitHub to host images for your README.MD
