### ISSUE TITLE
Threads fail to access tuples if there was a local tuple in the call stack with the same name

### ISSUE THREAD

**Issue by Taywee** [jwoehr/ublu#18]
Given the following functions:

```
FUNC first ( ) $[
    second ( )
]$

FUNC second ( ) $[
    put -to @val foo
    TASK -to NULL: -start $[
        put @val
    ]$
]$
```

A call to `first` produces:

```
> first ( )
foo
```

But, if I add a LOCAL @val to `first`, even if it does nothing:

```
FUNC first ( ) $[
    LOCAL @val
    second ( )
]$

FUNC second ( ) $[
    put -to @val foo
    TASK -to NULL: -start $[
        put @val
    ]$
]$
```

```
> first ( )
null
```

This breaks the ability of threads to reliably deal with the tuple stack, as a local of the same name can kill it.  I've also noticed that it varies; if I add a sleep to `first` after the call to `second`, it will work as expected, if there was previously a non-local `@val`, that previous value will be accessed instead of the local one.  My guess is that this occurs because the main thread kills the tuple stack for `@val` before the child thread has a chance to access it.

I couldn't find a way for threads to access tuple variables that they don't exclusively control without risk of the tuples being mutated under them.  Example of weird behavior with global state existing:

```
put -to @val baz

FUNC localfirst ( ) $[
    LOCAL @val
    second ( )
]$

FUNC first ( ) $[
    second ( )
]$

FUNC second ( ) $[
    put -to @val foo
    TASK -to NULL: -start $[
        put @val
    ]$
]$
```

```
> localfirst ( )
baz
> first ( )
foo
> localfirst ( )
foo
```

So which tuple is accessed also changes based on order of calls.

**Comment by jwoehr** [comment]
_LOCAL variables can be used as arguments to functions called from within the LOCAL-declaring block, but they cannot be used as arguments passed to other threads (see thread and TASK). The LOCAL variable does not exist in the context of the new thread_. http://www.softwoehr.com/softwoehr/oss/ubludoc/ubluref.html#LOCAL

**Comment by jwoehr** [comment]
Ublu is "call-by-reference" not "call-by-value". This is weird in the context of modern language design, but it works, you just have to handle things differently.

**Comment by Taywee** [comment]
Look at the example; the local variable isn't ever being used at all.  The behavior is incurred by having an unused LOCAL of the wrong name somewhere in the call stack at all.  The thread breaks just by the LOCAL existing.

**Comment by Taywee** [comment]
Ah, I see what's happening:

```
FUNC first ( ) $[
    LOCAL @val
    put -to @val foo
    put @val
    second ( )
    put @val
]$

FUNC second ( ) $[
    put -to @val bar
]$
```

```
> first ( )
foo
bar
> 
```

So called functions access caller's LOCAL tuples when they don't declare them local to their own block.  Seems really dangerous, as you can't safely call any function without knowing all of its source code, and you can't use any non-LOCAL tuples without risking stomping on your caller, which also means that it's not safe to use a TASK or thread from within a function without either not touching any external tuples or examining all the code in every environment that uses threads to be sure there won't be any LOCAL name conflicts in the call stack.  I'm not sure if there is a universally safe way to share tuples within a function with another thread, as you are required to use dynamically scoped variables, but you can accidentally stomp on lexically scoped tuples above in the process and still not get the value to child threads as a result.

**Comment by jwoehr** [comment]
Your second comment is accurate. Blocks are nested; they are frames on a stack. The environment of an enclosing block is inherited by child blocks. So a LOCAL in an enclosing block is much as if it were a global to an enclosed block.

This is weird in modern language design, but it's not dysfunctional. It's part-and-parcel of the nature of call-by-reference. It requires that **functions designed to write to globals receive the global as an argument in their argument list**.

More and more I have functions push to and pop from the stack.

Of course, this latter practice requires that the called function anticipate this and quickly do a `tuple -assign @somelocal @@arg` because argument passing is by token pasting, ergo, repetitive use of `@@arg` if that argument is passed as the stack-pop symbol `~` results in multiple stack pops!

Weird .. but not invalid. You just have to _choose an Ublu style_ and _employ that style consistently_!

**Comment by jwoehr** [comment]
You might examine some of the longer pieces of code that I'm writing these days, e.g., the test suite and the [test result display program](https://github.com/jwoehr/ublu/blob/master/examples/test/suite/testresults.ublu) (though you won't be able to run that unless I show you how to set up the test suite, it's not yet complete nor documented, but what's there runs very prettily).

**Comment by jwoehr** [comment]
Oh, and keep up with checkouts! As i author the test suite, guess what?! I find bugs and fix them!! And also add features that the test suite makes indispensible.

**Comment by jwoehr** [comment]
Thanks again for all your help, you provide invaluable feedback!

**Comment by jwoehr** [comment]
Thinking about this more last night.

I have not emphasized enough the tuple stack.

Tuples have existence independent of mapping. LOCAL and global are mappings of tuple _names_. The tuple continues to exist even if it drops off the map or is hidden by another mapping. One way to access a tuple is to push it to the tuple stack and then pop it.

**Comment by Taywee** [comment]
So what is the safe way to pass values into a TASK?  I have to create a global in order to get the value in:

```
FUNCTION myfunction ( ) $[
    LOCAL @mytuple
    # Stuff happens with @mytuple here
    TASK -to NULL: -start $[
        # This code needs to access @mytuple
    ]$
]$
```

I can't safely access the stack from inside the thread, I can't use external LOCALs from inside the thread.  As far as I know, the only thing I can do is create or use a global, but I have no guaranteed way of grabbing a global unless I examine the entire call stack for every invocation.  All I really need here is a safe, isolated way of passing variables into a child TASK irrespective of tuple context.  The example you gave:

```
FUNC killme ( ms  ) $[
    TASK -to NULL: -start $[ sleep -m @@ms exit ]$
]$
```

If I try to add utility functions:

```
FUNC killinseconds ( seconds ) $[
    LOCAL @milliseconds
    eval -to @milliseconds * @@seconds 1000
    killme ( @milliseconds )
]$

# Same, but uses global instead of LOCAL
FUNC killinsecondsglobal ( seconds ) $[
    eval -to @milliseconds * @@seconds 1000
    killme ( @milliseconds )
]$

```

Both of these fail with NullPointerExceptions.  I get the paradigm, and it usually works for me, but I don't see any way for a thread to receive a value (other than formatting it in as a literal in a string and calling it with `thread`) that is safe.

**Comment by jwoehr** [comment]
I see your point. Thinking about this.

**Comment by jwoehr** [comment]
ha! just creating a global on the fly works. You could even declare the global at the top of the file just to make it clear the name is reserved.
```
FUNC killme ( ms  ) $[
    put -to @MS @@ms
    TASK -to NULL: -start $[ sleep -m @MS exit ]$
]$
```

**Comment by Taywee** [comment]
That does work, as long as @MS did not exist as a LOCAL anywhere else in the call stack.  I was considering namespaced globals (like `@static_killme_ms`, perhaps) that are unlikely to exist anywhere already or be modified from somewhere else.  An ideal solution, for me, would be some way to explicitly pass tuples to a thread or TASK (or even a single tuple, as we can make a list if we need multiple), rather than having to rely on any shared environment.  Thread resource sharing is painful for any programming language, and would be ideally avoided to the greatest degree possible.

**Comment by jwoehr** [comment]
Let me think about that. I can probably create a global tuple bag with an immutable token.

**Comment by jwoehr** [comment]
Pushed a change to TASK adding -local

```
# TASK to exit Ublu after a number of milliseconds
FUNC killme ( ms ) $[
    TASK -to NULL: -local @ms @@ms -start $[
        put -n ${ value of @ms is }$ put @ms
        sleep -m @ms exit
    ]$
]$
# This works
FUNC killinseconds ( seconds ) $[ eval -to ~ * @@seconds 1000 killme ( ~ ) ]$
#This fails
FUNC killinseconds2 ( seconds ) $[ LOCAL @ms eval -to @ms * @@seconds 1000 killme ( @ms ) ]$
```

**Comment by jwoehr** [comment]
Okay, think I've got it working now!
```
# TASK to exit Ublu after a number of milliseconds
FUNC killme ( ms ) $[
    TASK -to NULL: -local @ms @@ms -start $[
	    put -n ${ value of @ms is }$ put @ms
		sleep -m @ms exit
	]$
]$

# This works
FUNC killinseconds ( seconds ) $[ eval -to ~ * @@seconds 1000 killme ( ~ ) ]$

# This works too
FUNC killinseconds2 ( seconds ) $[ LOCAL @ms eval -to @ms * @@seconds 1000 killme ( @ms ) ]$

```

**Comment by jwoehr** [comment]
Of course, check out the latest.

**Comment by jwoehr** [comment]
Fixed
