### ISSUE TITLE
subsystem command does not populate subsystem attributes without a refresh

### ISSUE THREAD

**Issue by Taywee** [jwoehr/ublu#19]
The subsystem command doesn't populate most of the subsystem's attributes without a `-refresh` being run:

```
> subsys -as400 @as400 -to @subsys -new -subsyspath /QSYS.LIB/QINTER.SBSD
> @subsys -query status
null
> @subsys -refresh
> @subsys -query status
*ACTIVE
```

This isn't necessarily a bug in the code, but the documentation doesn't explain this, so it can be confusing.  This should either be changed in the code (to refresh the subsystem before returning it in  `getSubsystem`) or in the documentation (explaining that getting the subsystem doesn't populate most of its data, and an initial `-refresh` is necessary).  I think the former makes a little more sense, as this means that there isn't a way to access a subsystem's status or some other attributes without assigning to a tuple (though that may be desirable).

**Comment by Taywee** [comment]
This does also make the subsystem's `-list` command show "null" for the last field of all subsystems.  It might make sense to refresh them all in the SubsystemArrayList too where relevant.

**Comment by jwoehr** [comment]
Valid, and made changes:
Both `-new` and `-list` now refresh any subsystem object returned.

**Comment by jwoehr** [comment]
Made one small extra fix right now, was not checking for subsystem existence before trying refresh.

**Comment by jwoehr** [comment]
Fixed.
