### ISSUE TITLE
gensh allowing variable input to glob

### ISSUE THREAD

**Issue by Taywee** [jwoehr/ublu#20]
Because the invocation of the jvm doesn't quote the gensh_runtime_opts, any splats or other relevant characters in passed-in values will glob on the filesystem.  This is particularly troublesome for regex operation.  Maybe a set -o noglob or something should be specified, or a way to pass gensh_runtime_opts into ublu as a single raw string should be devised.

## Sample of problem:

foo.ublu:

```
FUNC foo ( argument ) $[
    put @@argument
]$
```

ublu exec:

```
> gensh -to foo.sh -path /opt/ublu/ublu.jar -includepath $SCRIPTDIR -optr a ARGUMENT @argument ${ Example argument }$ ${ foo.sh: example script }$ foo.ublu ${ foo ( @argument ) }$
```

```sh
$ ls
alpha  beta  foo.sh  foo.ublu

$ sh foo.sh silent -a 'this is a test'  
this is a test

$ sh foo.sh silent -a 'this is a * test'
this is a alpha beta foo.sh foo.ublu test

$ sh foo.sh silent -a "'this is a * test'"
'this is a alpha beta foo.sh foo.ublu test'

$ sh foo.sh silent -a "'this is a \* test'" 
'this is a \* test'

$ sh foo.sh silent -a 'this is a \* test' 
this is a \* test
```

If we put `set -o noglob` above the invocation:

```sh
$ sh foo.sh silent -a 'this is a * test' 
this is a * test
```

**Comment by jwoehr** [comment]
Thanks for spotting this. Not sure which is best. Maybe a `gensh` option to choose "quote/noquote gensh_runtime_opts" ?

**Comment by Taywee** [comment]
Well, as it is, you can use `-prelude ${ set -o noglob }$` on `gensh` execution to ensure that it gets set before invocation.  I'm just wondering if that should be default.  I can't imagine there's much good use for globbing being enabled at all within a gensh script.  Any desired globbing should be done in the user shell side before invocation of the script entirely.

**Comment by jwoehr** [comment]
> use -prelude `${ set -o noglob }$` on `gensh` execution 

That doesn't work because `gensh` checks for superfluous arguments before processing any.

And that seems to be a major point: when a `gensh`-generated script receives its arguments, they are already globbed, right?

If I am correct about that, we apparently must treat this as a documentation issue: "If the command line to a `gensh`-generated script contains globbable arguments (e.g., * , ? ) you do not wish to have globbed, you must set -o noglob in your bash or ksh shell prior to script invocation." (with examples)

**Comment by Taywee** [comment]
`-prelude` isn't a superfluous argument, it's a standard gensh feature, allowing you to execute shell commands between argument setting arguments and calling ublu.

> And that seems to be a major point: when a gensh-generated script receives its arguments, they are already globbed, right?
They may be, but in current execution, they are globbed twice.  They are globbed when you call the script by the external shell, and they are globbed again on invocation of ublu:

```sh
# Invocation
# The ${gensh_runtime_opts} call here is where globbing is happening in the script
java -Dublu.includepath="$SCRIPTDIR" -jar /opt/ublu/ublu.jar ${gensh_runtime_opts} include ${SILENT}sysshep/msgq.ublu sysshep.msgq \( @properties @msgqueue @timefile \) 
```

And setting `set -o noglob` won't prevent this.  They will prevent expansion in the calling shell, but the called shell script will execute in a different shell process with globbing turned on, still exposing the issue.  Note that in my example above, globbing is happening even when everything is properly quoted.  The backslash escape doesn't work, but prevents globbing because no filenames have any backslashes at the beginning (otherwise it would expand to those).  Note the same example with the `-prelude` use:

```
> gensh -to foo.sh -path /opt/ublu/ublu.jar -includepath $SCRIPTDIR -optr a ARGUMENT @argument ${ Example argument }$ -prelude ${ set -o noglob }$ ${ foo.sh: example script }$ foo.ublu ${ foo ( @argument ) }$
```

```sh
$ tail -n 8 foo.sh
SCRIPTDIR=$(CDPATH= cd "$(dirname "$0")" && pwd)

# Prelude commands to execute before invocation
set -o noglob

# Invocation
java${JVMOPTS}${JVMPROPS} -Dublu.includepath="$SCRIPTDIR" -jar /opt/ublu/ublu.jar ${gensh_runtime_opts} include ${SILENT}foo.ublu foo \( @argument \) 
exit $?

$ sh foo.sh silent -a 'this is a * test'
this is a * test
```

**Comment by jwoehr** [comment]
No, I didn't mean `-prelude` was superfluous, I meant a `*` would generate superfluous arguments.
But you're right, d'oh :) Brain not working today, too many crises :) Yes, quoting 'em doesn't protect 'em from what the `gensh` script does with 'em later. So -prelude works. I can add a -noglob argument to `gensh` that adds in that sort of thing, or I can make noglob the default and add a `-glob` argument to `gensh`. OR we can treat it as a documentation issue.

**Comment by Taywee** [comment]
I'm fine with either, though I think that noglob should be the default behavior, as getting your quoted arguments globbed after the fact is never what you'd expect by default.  I'm feeling better now that I realize there's an effective workaround (and a portable one, as `set -o noglob` is POSIX-defined).

**Comment by jwoehr** [comment]
Yes, it is POSIX. And you're right, probably noglob should be default seeing as there are so many chances someone will want to pass an arg like *NOMAX to an Ublu script.

**Comment by jwoehr** [comment]
96330111455a3adafbc97d202574289908a8a29d implements

**Comment by jwoehr** [comment]
```
$ ./foo.sh
Option -a ARGUMENT is a required option but is not present.
foo.sh: example script 
This shell script was autogenerated Fri Nov 09 15:46:25 MST 2018 by jwoehr.
Usage: ./foo.sh [glob] [silent] [-h] [-X...] [-Dprop=val] -a ARGUMENT
	where
	-h		display this help message and exit 0
	-X xOpt		pass a -X option to the JVM (can be used many times)
	-D some.property="some value"	pass a property to the JVM (can be used many times)
	-a ARGUMENT	Example argument  (required option)
---
If the keyword 'glob' appears ahead of all other options and arguments, only then will arguments be globbed by the executing shell (noglob default).
If the keyword 'silent' appears ahead of all options except 'glob' (if the latter is present), then included files will not echo and prompting is suppressed.
Exit code is the result of execution, or 0 for -h or 2 if there is an error in processing options.
This script sets $SCRIPTDIR to the script's directory prior to executing prelude commands and Ublu invocation.
```

**Comment by jwoehr** [comment]
Fixed.
