### ISSUE TITLE
ftp command tries to fetch full path

### ISSUE THREAD

**Issue by Taywee** [jwoehr/ublu#9]
When using `ftp -get` with an absolute path, the command fetches from an absolute path to an absolute path, rather than to the local directory (which is more expected behavior with FTP).  This is very likely not desired.  (for instance, if I use ftp -get /tmp/testfile.txt, it fetches it from the system's /tmp/testfile.txt to the local machine's /tmp/testfile.txt, regardless of the current working directory.  This won't work if you're trying to fetch a file by absolute path to a directory that doesn't exist on the local machine.  I just ran into this issue with trying to fetch /QIBM/qzrdhasm/qzrdhasm.log from an as400 machine)

**Comment by jwoehr** [comment]
The ftp command is broken in a couple of ways in that it is partly broken in JTOpen itself. But I think if you use the `-to localfilepath` dashcommand it will work.

**Comment by Taywee** [comment]
`-tofile` would probably work.  I didn't see that one.  I think I tried `-to` and it just redirected the text output of the command (eg. the "226 File transfer completed successfully." text).  As `-tofile` covers it, I'll close this issue.  It's not the ideal default behavior, but it shouldn't cause too many problems, as most interactive use will probably use relative paths (or just an FTP program) and most scripted use should use -tofile anyway.

**Comment by jwoehr** [comment]
The `-tofile` and `-to` dichotomy arises from the fact that `-to` interprets a tuple as a the user wanting the output in a tuple. It interprets different forms as different types of datasinks. `-tofile` means "any way I provide the arg, I mean a file". The way I coded FTP (shudder) is that if `-to` points to a file datasink, the output file is set to that. Other than that, `-to` redirects the text output of the command. Ugh. Try `-tofile` and see if it works.
